# Generated by Django 4.2.1 on 2023-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatGptKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_key", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("character_long", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("tech_name", models.CharField(max_length=255)),
                ("stars", models.IntegerField()),
                ("review_writing_style", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("flag", models.BooleanField(default=False)),
            ],
        ),
    ]
