# Generated by Django 4.2.1 on 2023-06-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GMBDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("brand_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("flag", models.BooleanField(default=False)),
            ],
        ),
    ]
