# Generated by Django 4.2.1 on 2023-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_yourmodel_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGptKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_key", models.CharField(max_length=10000)),
            ],
        ),
    ]
