# Generated by Django 4.2.1 on 2023-06-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_gmbdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmbdescription",
            name="sco_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
