# Generated by Django 4.2.1 on 2023-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatgptkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='character_long',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='keywords',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='review_writing_style',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='tech_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
