# Generated by Django 4.2.1 on 2023-06-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gmbdescription_sco_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmbdescription',
            old_name='sco_description',
            new_name='seo_description',
        ),
    ]
